services:

  apache:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ./:/app:delegated
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./web/css:/app/web/css
    ports:
      - '8080:80'

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=fitstagram
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
        PMA_HOST: mysql
        PMA_USER: 'root'
        UPLOAD_LIMIT: 512M
    links:
      - mysql:db
    ports:
      - "8888:80"

  tailwind:
    build:
      context: ./tailwind
      dockerfile: Dockerfile
    volumes:
      - ./tailwind:/app
      - ./web/css:/app/output
      - ./views:/app/views
      - tailwind-node-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run watch"
    tty: true

volumes:
  mysql-data:
  tailwind-node-modules:
