// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Project Fitstagram {
database_type: "MySQL"
}

Table Media_File {
  id integer [pk, increment]
  media_path varchar
  name varchar [not null]
  post_id integer [not null, ref: > Post.id]
}

Table Tag {
    id integer [pk, increment]
    created_by integer [not null, ref: > User.id]
    name varchar [not null, unique]
    created_at timestamp
}

Table Post_Tag {
    post_id integer [not null, ref: > Post.id]
    tag_id integer [not null, ref: > Tag.id]
    created_at timestamp
    updated_at timestamp [default: `CURRENT_TIMESTAMP`]
    Indexes {
        (post_id, tag_id) [pk, unique]
    }
}

Table Post {
  id integer [pk, increment]
  created_by integer [not null, ref: > User.id]
  is_private boolean [not null]
  is_group_post boolean [not null]
  upvote_count integer [default: 0]
  downvote_count integer [default: 0]
  description varchar
  place varchar
  deleted boolean 
  created_at timestamp
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}

Table User {
    id integer [pk, increment]
    username varchar [not null]
    email varchar [not null]
    password_hash varchar [not null]
    password_reset_token varchar
    verification_token varchar [not null]
    auth_key varchar [not null]
    active boolean 
    deleted boolean 
    banned boolean 
    created_at timestamp
    updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}

Table Post_Vote {
  up boolean [not null]
  voted_by integer [not null, ref: > User.id]
  post_id integer [not null, ref: > Post.id]
  created_at timestamp
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
 
  Indexes {
    (post_id, voted_by) [pk, unique]
  }
}

Table Comment {
  id integer [pk, increment]
  content varchar [not null]
  created_by integer [not null, ref: > User.id]
  post_id integer [not null, ref: > Post.id]
  deleted boolean 
  created_at timestamp
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}

Table Group {
  id integer [pk, increment]
  name varchar [not null]
  owner_id integer [not null, ref: > User.id]
  active boolean
  deleted boolean
  banned boolean
  created_at timestamp 
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}

Table Group_Users {
  group_id integer [not null, ref: > Group.id]
  user_id integer [not null, ref: > User.id]
  created_at timestamp 
  Indexes {
    (user_id, group_id) [pk,unique]
  }
}

Table Group_Join_Request {
  id integer [pk, increment]
  group_id integer [not null, ref: > Group.id]
  created_by integer [not null, ref: > User.id]
  pending boolean
  declined boolean
  accepted boolean
  created_at timestamp
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}

Table Group_Post {
    group_id integer [not null, ref: > Group.id]
    post_id integer [not null, ref: > Post.id]
    Indexes {
        (group_id, post_id) [pk,unique]
    }
}

Table Permitted_User {
    user_id int [ref: > User.id] 
    permitted_user_id int [ref: > User.id] 
    
    Indexes {
    (user_id, permitted_user_id) [pk, unique] 
    }
}



